# Generated by Django 2.2 on 2019-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('url_code', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('full_url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
